using StockSim.Engine.Models;
using StockSim.Engine.Utils;

namespace StockSim.Engine.Services;

/// <summary>
/// Simulates aggregate AI trader behavior that affects market dynamics.
/// Spec 7.1-7.2: 14 trader types, each with distinct behavior.
///
/// AI traders don't have individual portfolios or orders.
/// They affect the market through aggregate adjustments to:
///   - Spreads (Market Maker, HFT)
///   - Volume (all)
///   - Price pressure (Retail sentiment, Institutional flow, Hedge Funds, etc.)
///   - Short interest (Hedge Fund L/S, Activist Short Seller)
///
/// Types implemented:
///   1. Market Maker (7.2.1)       — liquidity, spreads
///   2. HFT (7.2.2)               — ultra-tight spreads on large caps, withdrawal risk
///   3. Pension Fund (7.2.3)       — dip-buying Blue Chips, quarterly rebalance
///   4. Mutual Fund (7.2.4)        — mandate-based buying, window dressing
///   5. Index/ETF Fund (7.2.5)     — passive flows amplify trends
///   6. Hedge Fund L/S (7.2.6)     — short interest, deleverage risk
///   7. Hedge Fund Macro (7.2.7)   — sector bets based on macro
///   8. Sovereign Wealth (7.2.8)   — crisis dip-buying
///   9. Day Trader (7.2.9)         — volume at open/close, intraday momentum
///  10. Swing Trader (7.2.10)      — multi-day trend following
///  11. Algorithmic/Quant (7.2.11) — momentum + mean reversion
///  12. Arbitrageur (7.2.12)       — keeps correlations intact
///  13. Retail Trader (7.2.13)     — FOMO, panic, trend following
///  14. Insider Trader (7.2.14)    — pre-event volume anomalies
/// </summary>
public class AITraderEngine
{
    private readonly Random _rng;
    private readonly Logger _log = new("AITrader");

    // --- Aggregate state trackers ---

    // Retail sentiment: -1 (panic) to +1 (euphoria)
    private float _retailSentiment = 0f;
    // Institutional flow: slow-moving capital, -1 selling, +1 buying
    private float _institutionalFlow = 0f;
    // Hedge fund leverage stress: 0 (calm) to 1 (deleverage cascade)
    private float _hedgeFundStress = 0f;
    // Macro hedge fund sector bias: positive = bullish rotation, negative = defensive
    private float _macroSectorBias = 0f;
    // Day trader momentum tracker per tick
    private int _ticksInDay = 0;

    public float RetailSentiment => _retailSentiment;
    public float InstitutionalFlow => _institutionalFlow;
    public float HedgeFundStress => _hedgeFundStress;

    /// <summary>Aggression multiplier. Higher = more volume, larger price impact. Set from NewGame.</summary>
    public float AggressionMultiplier { get; set; } = 1.0f;

    /// <summary>Current tick within trading day (0-389). Set by GameLoop for time-of-day spread dynamics.</summary>
    public int CurrentDayTick { get; set; }

    /// <summary>Symbols/sectors affected by active events this tick. Set by GameLoop.</summary>
    public HashSet<string> EventAffectedSymbols { get; } = new();
    public HashSet<string> EventAffectedSectors { get; } = new();
    public Dictionary<string, EventSeverity> EventSeverityBySymbol { get; } = new();

    /// <summary>News events generated by AI traders this tick (block trades, short reports, etc.).</summary>
    public List<GameEvent> NewsThisTick { get; } = new();

    /// <summary>Day counter for quarterly effects (window dressing, rebalancing).</summary>
    public int DayCount { get; set; }

    public AITraderEngine(int seed)
    {
        _rng = new Random(seed);
    }

    /// <summary>
    /// Called each market tick. Runs all AI trader behaviors.
    /// </summary>
    public void Tick(IReadOnlyList<Stock> stocks, IReadOnlyList<GameEvent> activeEvents, bool isMarketOpen)
    {
        NewsThisTick.Clear();

        if (!isMarketOpen) return;
        _ticksInDay++;

        // Update aggregate state
        UpdateRetailSentiment(activeEvents);
        UpdateInstitutionalFlow(activeEvents);
        UpdateHedgeFundStress(stocks, activeEvents);
        UpdateMacroSectorBias(activeEvents);

        foreach (var stock in stocks)
        {
            // Liquidity providers
            ApplyMarketMaker(stock);        // 7.2.1
            ApplyHFT(stock);                // 7.2.2

            // Institutional
            ApplyInstitutionalFlow(stock);  // 7.2.3-7.2.5 (Pension, Mutual, Index)
            ApplyHedgeFundLS(stock);        // 7.2.6
            ApplyHedgeFundMacro(stock);     // 7.2.7
            ApplySovereignWealth(stock);    // 7.2.8

            // Professional
            ApplyDayTrader(stock);          // 7.2.9
            ApplySwingTrader(stock);        // 7.2.10
            ApplyAlgorithmicTrading(stock); // 7.2.11
            ApplyArbitrageur(stock);        // 7.2.12

            // Retail & Special
            ApplyRetailPressure(stock);     // 7.2.13
            ApplyInsiderTraderAI(stock, activeEvents); // 7.2.14

            // Stop-loss cascade simulation
            ApplyStopCascadePressure(stock);
        }
    }

    /// <summary>Called at market close each day for daily-resolution behaviors.</summary>
    public void TickDay(IReadOnlyList<Stock> stocks, IReadOnlyList<GameEvent> activeEvents, DateTime? gameTime = null)
    {
        DayCount++;
        _ticksInDay = 0;

        // Quarterly window dressing (Spec 7.2.4: last 3-5 days of quarter)
        if (DayCount % 60 >= 55) // Roughly every 60 trading days = 1 quarter
        {
            ApplyWindowDressing(stocks);
        }

        // Activist short seller: rare event generation (Spec 7.2.15)
        TryGenerateShortReport(stocks);

        // Corporate buyback pressure (Spec 7.2.16)
        ApplyCorporateBuybacks(stocks);

        // Tax-loss harvesting (December) + January effect
        if (gameTime.HasValue)
            ApplyTaxLossHarvesting(stocks, gameTime.Value);
    }

    // =====================================================
    // 1. MARKET MAKER (Spec 7.2.1)
    // =====================================================

    private void ApplyMarketMaker(Stock stock)
    {
        var baseSpreadPct = stock.LiquidityScore switch
        {
            >= 9 => 0.0005m,  // 0.05% mega caps
            >= 7 => 0.001m,   // 0.10% large caps
            >= 5 => 0.002m,   // 0.20% mid caps
            >= 3 => 0.004m,   // 0.40% small caps
            _ => 0.008m,      // 0.80% micro caps
        };

        // Volatility widens spread
        var volMultiplier = 1m + stock.BaseVolatility * 5m;

        // Time-of-day: wider at open/close (real market behavior)
        var t = CurrentDayTick;
        decimal todMult = t < 30 ? 1.5m - (t / 30m * 0.4m) :    // 1.5x → 1.1x (first 30 min)
                          t > 360 ? 1.1m + ((t - 360) / 30m * 0.3m) : // 1.1x → 1.4x (last 30 min)
                          1.0m;
        volMultiplier *= todMult;

        // Event-driven spread widening: major news → market makers widen
        if (EventSeverityBySymbol.TryGetValue(stock.Symbol, out var sev) ||
            EventAffectedSectors.Contains(stock.Sector))
        {
            var eventMult = sev switch
            {
                Models.EventSeverity.Major => 2.5m,
                Models.EventSeverity.Moderate => 1.6m,
                Models.EventSeverity.Minor => 1.2m,
                _ => 1.0m,
            };
            volMultiplier *= eventMult;
        }

        // Hedge fund stress widens spreads (liquidity withdrawal)
        if (_hedgeFundStress > 0.3f)
            volMultiplier *= 1m + (decimal)_hedgeFundStress;

        var noise = 1m + (decimal)(_rng.NextDouble() * 0.1 - 0.05);
        var halfSpread = stock.CurrentPrice * baseSpreadPct * volMultiplier * noise;
        halfSpread = Math.Max(halfSpread, 0.005m);

        stock.BidPrice = Math.Round(stock.CurrentPrice - halfSpread, 2);
        stock.AskPrice = Math.Round(stock.CurrentPrice + halfSpread, 2);
        stock.BidPrice = Math.Max(stock.BidPrice, 0.01m);
        if (stock.AskPrice <= stock.BidPrice)
            stock.AskPrice = stock.BidPrice + 0.01m;

        var mmVolume = (long)(stock.AverageVolume * (0.001 + _rng.NextDouble() * 0.002));
        stock.DayVolume += Math.Max(mmVolume, 1);
    }

    // =====================================================
    // 2. HFT (Spec 7.2.2)
    // =====================================================

    private void ApplyHFT(Stock stock)
    {
        // HFT only active on liquid stocks (Large Cap+)
        if (stock.LiquidityScore < 6) return;

        // HFT tightens spreads further on large caps
        if (_rng.NextDouble() < 0.3)
        {
            var tighten = stock.CurrentPrice * 0.0001m * (decimal)(_rng.NextDouble());
            stock.BidPrice = Math.Min(stock.BidPrice + tighten, stock.CurrentPrice - 0.01m);
            stock.AskPrice = Math.Max(stock.AskPrice - tighten, stock.CurrentPrice + 0.01m);
        }

        // HFT adds high volume with no price impact
        var hftVolume = (long)(stock.AverageVolume * 0.003 * _rng.NextDouble());
        stock.DayVolume += hftVolume;

        // HFT withdrawal during stress (Spec 7.2.2: can disappear → flash crash risk)
        if (_hedgeFundStress > 0.5f && _rng.NextDouble() < _hedgeFundStress * 0.3)
        {
            // Widen spread — liquidity vacuum
            var widen = stock.CurrentPrice * 0.002m;
            stock.BidPrice -= widen;
            stock.AskPrice += widen;
            stock.BidPrice = Math.Max(stock.BidPrice, 0.01m);
        }
    }

    // =====================================================
    // 3-5. INSTITUTIONAL (Spec 7.2.3-7.2.5)
    // =====================================================

    private void UpdateInstitutionalFlow(IReadOnlyList<GameEvent> activeEvents)
    {
        float contrarian = 0f;
        foreach (var evt in activeEvents)
            contrarian -= evt.Sentiment * 0.002f;

        _institutionalFlow += contrarian;
        _institutionalFlow *= 0.998f;
        _institutionalFlow = Math.Clamp(_institutionalFlow, -0.5f, 0.5f);
    }

    private void ApplyInstitutionalFlow(Stock stock)
    {
        if (Math.Abs(_institutionalFlow) < 0.02f) return;
        if (stock.FairValue <= 0) return;

        var deviation = (stock.CurrentPrice - stock.FairValue) / stock.FairValue;
        if (Math.Abs(deviation) < 0.05m) return;

        // Pension funds (7.2.3): Blue Chips, Dividend Aristocrats
        var weight = 1.0m;
        if (stock.Traits.Contains("Blue Chip")) weight = 2.0m;
        if (stock.Traits.Contains("Dividend Aristocrat")) weight = 1.5m;
        if (stock.Traits.Contains("Speculative")) weight = 0.3m;
        if (stock.Traits.Contains("Defensive")) weight *= 1.3m;
        if (stock.Traits.Contains("Cash Cow")) weight *= 1.4m;
        if (stock.Traits.Contains("ESG Leader")) weight *= 1.2m;
        if (stock.Traits.Contains("Controversy Magnet")) weight *= 0.6m;
        if (stock.Traits.Contains("Compounder")) weight *= 1.3m;
        if (stock.Traits.Contains("Debt Heavy")) weight *= 0.7m;

        // Mutual funds (7.2.4): mandate-driven
        if (stock.Traits.Contains("Growth Stock") || stock.RevenueGrowth > 0.10m) weight *= 1.2m;
        if (stock.Traits.Contains("Value Stock") || (stock.PERatio > 0 && stock.PERatio < 15)) weight *= 1.3m;

        // Index/ETF funds (7.2.5): proportional to market cap
        var mcapWeight = stock.MarketCap > 100_000_000_000m ? 1.5m :
                         stock.MarketCap > 10_000_000_000m ? 1.2m : 0.8m;
        weight *= mcapWeight;

        var pressure = -deviation * 0.00002m * weight * (decimal)_institutionalFlow;

        if (_rng.NextDouble() < 0.2)
        {
            stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * pressure, 2));
        }

        var instVolume = (long)(stock.AverageVolume * 0.001 * Math.Abs((double)_institutionalFlow));
        stock.DayVolume += Math.Max(instVolume, 0);
    }

    // =====================================================
    // 6. HEDGE FUND LONG/SHORT (Spec 7.2.6)
    // =====================================================

    /// <summary>Margin cascade events this tick (for news feed). Set by cascade logic.</summary>
    public List<string> MarginCascadeNewsThisTick { get; } = new();
    private int _marginCascadeNewsCooldown;

    /// <summary>Monetary policy stress input. Set by GameLoop from EconomicEngine.</summary>
    public float PolicyStressFactor { get; set; }

    private void UpdateHedgeFundStress(IReadOnlyList<Stock> stocks, IReadOnlyList<GameEvent> activeEvents)
    {
        MarginCascadeNewsThisTick.Clear();
        if (_marginCascadeNewsCooldown > 0) _marginCascadeNewsCooldown--;

        // Count severe negative events
        var negativeCount = 0;
        foreach (var evt in activeEvents)
            if (evt.Sentiment < -0.3f && evt.Severity >= EventSeverity.Moderate) negativeCount++;

        // Stress increases with negative events, decays slowly
        if (negativeCount > 2)
            _hedgeFundStress += 0.05f * negativeCount;

        // Monetary policy amplifier: Tightening increases base stress
        _hedgeFundStress += PolicyStressFactor * 0.002f;

        // Market-wide drawdown amplifier: broad declines compound stress
        var avgDayChange = stocks.Count > 0
            ? (float)stocks.Average(s => (double)s.DayChangePercent) : 0f;
        if (avgDayChange < -2f) // Market down >2%
            _hedgeFundStress += Math.Abs(avgDayChange) * 0.01f;

        // Cascade trigger: at high stress, forced selling creates MORE stress (positive feedback loop)
        if (_hedgeFundStress > 0.7f)
        {
            var cascadeBoost = (_hedgeFundStress - 0.7f) * 0.15f; // Self-reinforcing above 0.7
            _hedgeFundStress += cascadeBoost;

            // Generate cascade news at critical levels (max 1 per day via cooldown)
            if (_hedgeFundStress > 0.8f && _marginCascadeNewsCooldown <= 0 && _rng.NextDouble() < 0.002)
            {
                MarginCascadeNewsThisTick.Add(
                    $"MARGIN ALERT: Leveraged funds facing margin calls as market stress reaches elevated levels — forced liquidation reported across multiple desks");
                _marginCascadeNewsCooldown = 390; // 1 trading day cooldown
            }
        }

        _hedgeFundStress *= 0.995f; // Natural decay
        _hedgeFundStress = Math.Clamp(_hedgeFundStress, 0f, 1f);
    }

    private void ApplyHedgeFundLS(Stock stock)
    {
        // Hedge funds generate short interest (Spec 7.2.6)
        if (stock.FairValue > 0 && stock.CurrentPrice > stock.FairValue * 1.3m)
        {
            // Overvalued → short pressure
            if (_rng.NextDouble() < 0.05)
            {
                var shortPressure = stock.CurrentPrice * 0.00003m * (decimal)AggressionMultiplier;
                stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice - shortPressure, 2));
                // Increase short interest slightly
                stock.ShortInterest += stock.SharesOutstanding * 0.0001m * (decimal)_rng.NextDouble();
            }
        }

        // Undervalued → long pressure
        if (stock.FairValue > 0 && stock.CurrentPrice < stock.FairValue * 0.7m)
        {
            if (_rng.NextDouble() < 0.05)
            {
                var longPressure = stock.CurrentPrice * 0.00003m * (decimal)AggressionMultiplier;
                stock.CurrentPrice = Math.Round(stock.CurrentPrice + longPressure, 2);
            }
        }

        // Deleverage cascade during stress (Spec 7.2.6: margin call → forced selling)
        if (_hedgeFundStress > 0.5f && _rng.NextDouble() < _hedgeFundStress * 0.15)
        {
            // Sector leverage sensitivity: Real Estate, Financials, Tech take bigger hits
            var sectorLeverage = stock.Sector switch
            {
                "Real Estate" => 1.8m,
                "Financials" => 1.5m,
                "Technology" => 1.3m,
                "Luxury Goods" => 1.2m,
                _ => 1.0m,
            };

            // High-beta stocks (volatile) get hit harder in cascade
            var betaFactor = Math.Min(2.0m, stock.BaseVolatility / 0.02m);

            var deleveragePressure = stock.CurrentPrice * 0.0003m * (decimal)_hedgeFundStress * sectorLeverage * betaFactor;
            stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice - deleveragePressure, 2));
            stock.DayVolume += (long)(stock.AverageVolume * 0.02 * _hedgeFundStress * (double)sectorLeverage);
        }
    }

    // =====================================================
    // STOP-LOSS CASCADE SIMULATION
    // =====================================================

    /// <summary>
    /// Simulate AI stop-loss clustering at round numbers.
    /// When price approaches a cluster, downward pressure increases as AI stops trigger.
    /// </summary>
    private void ApplyStopCascadePressure(Stock stock)
    {
        var price = (double)stock.CurrentPrice;
        if (price <= 0) return;

        // Round number levels where stops cluster
        double[] levels = price switch
        {
            > 200 => new[] { Math.Floor(price / 50) * 50, Math.Floor(price / 25) * 25 },
            > 50 => new[] { Math.Floor(price / 25) * 25, Math.Floor(price / 10) * 10 },
            > 10 => new[] { Math.Floor(price / 10) * 10, Math.Floor(price / 5) * 5 },
            _ => new[] { Math.Floor(price), Math.Floor(price / 0.5) * 0.5 },
        };

        foreach (var level in levels)
        {
            if (level <= 0) continue;
            var distance = (price - level) / price; // Positive = price above level

            // Only apply pressure when price is just above a round number (within 1.5%)
            if (distance > 0 && distance < 0.015)
            {
                // Closer to level = stronger pressure (simulates stops triggering)
                var intensity = (0.015 - distance) / 0.015; // 0 to 1
                var pressure = stock.CurrentPrice * (decimal)(intensity * 0.0002 * (1 + _hedgeFundStress));
                stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice - pressure, 2));

                // Volume spike as stops trigger
                if (intensity > 0.5)
                    stock.DayVolume += (long)(stock.AverageVolume * 0.005 * intensity);
            }
        }
    }

    // =====================================================
    // 7. HEDGE FUND MACRO (Spec 7.2.7)
    // =====================================================

    private void UpdateMacroSectorBias(IReadOnlyList<GameEvent> activeEvents)
    {
        foreach (var evt in activeEvents)
        {
            if (evt.Type == EventType.Macro)
            {
                // Macro events drive sector rotation
                _macroSectorBias += evt.Sentiment * 0.01f;
            }
        }
        _macroSectorBias *= 0.997f;
        _macroSectorBias = Math.Clamp(_macroSectorBias, -1f, 1f);
    }

    private void ApplyHedgeFundMacro(Stock stock)
    {
        if (Math.Abs(_macroSectorBias) < 0.05f) return;
        if (_rng.NextDouble() > 0.05) return; // 5% of ticks

        // Sector rotation: bullish bias → growth/tech, bearish → defensive/utilities
        var sectorMultiplier = 0m;
        if (_macroSectorBias > 0)
        {
            // Bullish: buy growth sectors
            if (stock.Sector is "Technology" or "Consumer Goods" or "Luxury Goods")
                sectorMultiplier = 1.5m;
            else if (stock.Sector is "Utilities" or "Real Estate")
                sectorMultiplier = -0.5m; // Sell defensive
        }
        else
        {
            // Bearish: buy defensive, sell growth
            if (stock.Sector is "Utilities" or "Healthcare" or "Consumer Goods")
                sectorMultiplier = 1.0m;
            else if (stock.Sector is "Technology" or "Luxury Goods")
                sectorMultiplier = -1.0m;
        }

        // Cyclical trait: amplifies sector rotation effects
        if (stock.Traits.Contains("Cyclical"))
            sectorMultiplier *= 1.5m;
        // Defensive trait: dampens sector rotation
        if (stock.Traits.Contains("Defensive"))
            sectorMultiplier *= 0.5m;

        if (sectorMultiplier == 0) return;

        var pressure = stock.CurrentPrice * 0.00002m * (decimal)_macroSectorBias * sectorMultiplier;
        stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + pressure, 2));
    }

    // =====================================================
    // 8. SOVEREIGN WEALTH FUND (Spec 7.2.8)
    // =====================================================

    private void ApplySovereignWealth(Stock stock)
    {
        // Only act on large caps / blue chips
        if (stock.MarketCap < 10_000_000_000m) return;
        if (_rng.NextDouble() > 0.01) return; // Very rare per tick

        // Buy the dip: if market is stressed and stock is significantly down
        var dayReturn = stock.PreviousClose > 0
            ? (stock.CurrentPrice - stock.PreviousClose) / stock.PreviousClose
            : 0m;

        if (dayReturn < -0.03m) // Stock down >3%
        {
            // Sovereign wealth buying — stabilizing force
            var buyPressure = stock.CurrentPrice * 0.00005m;
            stock.CurrentPrice = Math.Round(stock.CurrentPrice + buyPressure, 2);
            stock.DayVolume += (long)(stock.AverageVolume * 0.002);
        }
    }

    // =====================================================
    // 9. DAY TRADER (Spec 7.2.9)
    // =====================================================

    private void ApplyDayTrader(Stock stock)
    {
        // Day traders active only in first 90 min (ticks 0-90) and last 60 min (ticks 330-390)
        if (_ticksInDay > 90 && _ticksInDay < 330) return;
        if (_rng.NextDouble() > 0.15) return; // 15% per tick during active windows

        var dayReturn = stock.PreviousClose > 0
            ? (stock.CurrentPrice - stock.PreviousClose) / stock.PreviousClose
            : 0m;

        // Need momentum to enter: >1% move
        if (Math.Abs(dayReturn) < 0.01m) return;

        // Day traders chase momentum — amplify the move
        var push = dayReturn * 0.00008m * (decimal)AggressionMultiplier;

        // Stronger on volatile / speculative stocks
        if (stock.BaseVolatility > 0.03m) push *= 1.5m;
        if (stock.Traits.Contains("Speculative")) push *= 2.0m;

        stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * push, 2));

        // Day traders add significant volume at open/close
        var dtVolume = (long)(stock.AverageVolume * 0.005 * _rng.NextDouble());
        stock.DayVolume += dtVolume;
    }

    // =====================================================
    // 10. SWING TRADER (Spec 7.2.10)
    // =====================================================

    private void ApplySwingTrader(Stock stock)
    {
        if (_rng.NextDouble() > 0.03) return; // 3% of ticks

        var dayReturn = stock.PreviousClose > 0
            ? (stock.CurrentPrice - stock.PreviousClose) / stock.PreviousClose
            : 0m;

        // Swing traders follow multi-day trends
        // If stock is trending (>2% day move), they pile in
        if (Math.Abs(dayReturn) > 0.02m)
        {
            var push = dayReturn * 0.00003m;
            // Momentum Stock trait: trends persist longer, stronger swing trader interest
            if (stock.Traits.Contains("Momentum Stock")) push *= 2.0m;
            stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * push, 2));
        }

        // Mean reversion: if a stock dropped >5%, swing traders buy the dip
        if (dayReturn < -0.05m && _rng.NextDouble() < 0.3)
        {
            var buyPush = stock.CurrentPrice * 0.00005m;
            stock.CurrentPrice = Math.Round(stock.CurrentPrice + buyPush, 2);
        }

        var swVolume = (long)(stock.AverageVolume * 0.002 * _rng.NextDouble());
        stock.DayVolume += swVolume;
    }

    // =====================================================
    // 11. ALGORITHMIC / QUANT TRADER (Spec 7.2.11)
    // =====================================================

    private void ApplyAlgorithmicTrading(Stock stock)
    {
        if (_rng.NextDouble() > 0.1) return;

        var dayReturn = stock.PreviousClose > 0
            ? (stock.CurrentPrice - stock.PreviousClose) / stock.PreviousClose
            : 0m;

        if (Math.Abs(dayReturn) < 0.001m) return;

        // Momentum algos: amplify trends
        var momentumPush = dayReturn * 0.00005m;
        stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * momentumPush, 2));

        // Mean reversion algos: dampen extremes (counteracts when move > 5%)
        if (Math.Abs(dayReturn) > 0.05m)
        {
            var reversion = -dayReturn * 0.00003m;
            stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * reversion, 2));
        }

        var algoVolume = (long)(stock.AverageVolume * 0.002 * _rng.NextDouble());
        stock.DayVolume += algoVolume;
    }

    // =====================================================
    // 12. ARBITRAGEUR (Spec 7.2.12)
    // =====================================================

    private void ApplyArbitrageur(Stock stock)
    {
        if (stock.FairValue <= 0) return;
        if (_rng.NextDouble() > 0.05) return;

        // Arb: push price toward fair value (keeps market efficient)
        var deviation = (stock.CurrentPrice - stock.FairValue) / stock.FairValue;
        if (Math.Abs(deviation) < 0.02m) return; // Only arb significant deviations

        var arbPush = -deviation * 0.00001m;
        stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + stock.CurrentPrice * arbPush, 2));
    }

    // =====================================================
    // 13. RETAIL TRADER (Spec 7.2.13)
    // =====================================================

    private void UpdateRetailSentiment(IReadOnlyList<GameEvent> activeEvents)
    {
        float eventImpact = 0f;
        foreach (var evt in activeEvents)
        {
            var weight = evt.Severity switch
            {
                EventSeverity.Major => 0.3f,
                EventSeverity.Moderate => 0.15f,
                EventSeverity.Minor => 0.05f,
                _ => 0.1f,
            };
            eventImpact += evt.Sentiment * weight;
        }

        _retailSentiment += eventImpact * 0.01f;
        _retailSentiment *= 0.999f;
        _retailSentiment = Math.Clamp(_retailSentiment, -1f, 1f);
    }

    private void ApplyRetailPressure(Stock stock)
    {
        if (Math.Abs(_retailSentiment) < 0.05f) return;

        var susceptibility = stock.BaseVolatility * 2m;
        if (stock.Traits.Contains("Speculative") || stock.Traits.Contains("Penny Stock"))
            susceptibility *= 2m;
        if (stock.Traits.Contains("Controversy Magnet"))
            susceptibility *= 1.5m; // More reactive to sentiment
        if (stock.Traits.Contains("Volatile"))
            susceptibility *= 1.3m;

        var pressurePerTick = (decimal)_retailSentiment * susceptibility * 0.0001m;

        if (_rng.NextDouble() < 0.3)
        {
            stock.CurrentPrice += stock.CurrentPrice * pressurePerTick;
            stock.CurrentPrice = Math.Max(stock.CurrentPrice, 0.01m);
            stock.CurrentPrice = Math.Round(stock.CurrentPrice, 2);
        }

        // FOMO / panic volume
        if (Math.Abs(_retailSentiment) > 0.2f)
        {
            var sentimentVolume = (long)(stock.AverageVolume * Math.Abs(_retailSentiment) * 0.005 * _rng.NextDouble());
            stock.DayVolume += Math.Max(sentimentVolume, 0);
        }
    }

    // =====================================================
    // 14. INSIDER TRADER AI (Spec 7.2.14)
    // =====================================================

    private void ApplyInsiderTraderAI(Stock stock, IReadOnlyList<GameEvent> activeEvents)
    {
        // Insider traders cause unusual volume BEFORE company events
        // Check if there's an active company event for this stock
        foreach (var evt in activeEvents)
        {
            if (evt.Type != EventType.Company) continue;
            if (!evt.AffectedSymbols.Contains(stock.Symbol)) continue;

            // If event just started (first few ticks), generate pre-event volume
            if (evt.RemainingMinutes > evt.DurationMinutes - 10)
            {
                // 30-50% chance per stock per tick that insider trading occurs
                if (_rng.NextDouble() < 0.02)
                {
                    // Unusual volume spike (visible to attentive players)
                    var insiderVolume = (long)(stock.AverageVolume * 0.01 * (1 + _rng.NextDouble()));
                    stock.DayVolume += insiderVolume;

                    // Slight price pressure in event direction (insiders know the outcome)
                    var insiderPush = stock.CurrentPrice * 0.00002m * (decimal)Math.Sign(evt.PriceEffect);
                    stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice + insiderPush, 2));
                }
            }
        }
    }

    // =====================================================
    // DAILY BEHAVIORS (called from TickDay)
    // =====================================================

    /// <summary>
    /// Spec 7.2.4: Window dressing — mutual funds buy winners, sell losers at quarter end.
    /// </summary>
    private void ApplyWindowDressing(IReadOnlyList<Stock> stocks)
    {
        foreach (var stock in stocks)
        {
            if (stock.Traits.Contains("ETF")) continue;

            var dayReturn = stock.PreviousClose > 0
                ? (stock.CurrentPrice - stock.PreviousClose) / stock.PreviousClose
                : 0m;

            // Buy winners (positive momentum stocks)
            if (dayReturn > 0.03m && _rng.NextDouble() < 0.3)
            {
                var push = stock.CurrentPrice * 0.001m;
                stock.CurrentPrice = Math.Round(stock.CurrentPrice + push, 2);
                stock.DayVolume += (long)(stock.AverageVolume * 0.01);
            }
            // Sell losers
            else if (dayReturn < -0.03m && _rng.NextDouble() < 0.3)
            {
                var push = stock.CurrentPrice * 0.001m;
                stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice - push, 2));
                stock.DayVolume += (long)(stock.AverageVolume * 0.01);
            }
        }

        _log.Debug("Window dressing active", new { dayCount = DayCount });
    }

    /// <summary>
    /// Spec 7.2.15: Activist short seller publishes short report on overvalued stock.
    /// Rare but high-impact event.
    /// </summary>
    private void TryGenerateShortReport(IReadOnlyList<Stock> stocks)
    {
        if (_rng.NextDouble() > 0.01) return; // ~1% daily = roughly every 100 trading days

        // Find an overvalued target
        var targets = stocks.Where(s =>
            !s.Traits.Contains("ETF") &&
            s.PERatio > 50 &&
            s.CurrentPrice > s.FairValue * 1.5m &&
            s.MarketCap > 1_000_000_000m
        ).ToList();

        if (targets.Count == 0) return;

        var target = targets[_rng.Next(targets.Count)];

        // Generate short report event
        var impact = -0.08f - (float)_rng.NextDouble() * 0.12f; // -8% to -20%
        var evt = new GameEvent
        {
            Type = EventType.Company,
            Severity = EventSeverity.Major,
            Sentiment = -0.8f,
            Headline = $"Activist short seller publishes critical report on {target.Name} ({target.Symbol}), alleging overvaluation",
            AffectedSymbols = new List<string> { target.Symbol },
            PriceEffect = impact,
            VolatilityMultiplier = 2.5f,
            VolumeMultiplier = 4.0f,
            DurationMinutes = 120,
            RemainingMinutes = 120,
            TriggeredAt = DateTime.MinValue, // Will be set by caller
        };
        NewsThisTick.Add(evt);

        // Increase short interest
        target.ShortInterest += target.SharesOutstanding * 0.02m;

        _log.Info("Short report generated", new { symbol = target.Symbol, impact });
    }

    /// <summary>
    /// Tax-loss harvesting: December selling pressure on YTD losers, January bounce-back.
    /// Real effect: stocks that performed worst in the year get sold in December for tax benefits.
    /// </summary>
    private void ApplyTaxLossHarvesting(IReadOnlyList<Stock> stocks, DateTime gameTime)
    {
        var month = gameTime.Month;
        if (month != 12 && month != 1) return;

        foreach (var stock in stocks)
        {
            if (stock.Traits.Contains("ETF")) continue;

            // YTD return approximation (using 20-day return as proxy)
            var ytdReturn = stock.Return20Day;

            if (month == 12 && ytdReturn < -0.05m) // December: sell losers
            {
                if (_rng.NextDouble() < 0.05) // 5% daily chance
                {
                    var sellPressure = stock.CurrentPrice * 0.0005m;
                    stock.CurrentPrice = Math.Max(0.01m, Math.Round(stock.CurrentPrice - sellPressure, 2));
                    stock.DayVolume += (long)(stock.AverageVolume * 0.005);
                }
            }
            else if (month == 1 && ytdReturn < -0.05m) // January: bounce back (buying oversold)
            {
                if (_rng.NextDouble() < 0.05)
                {
                    var buyPressure = stock.CurrentPrice * 0.0004m;
                    stock.CurrentPrice = Math.Round(stock.CurrentPrice + buyPressure, 2);
                    stock.DayVolume += (long)(stock.AverageVolume * 0.003);
                }
            }
        }
    }

    /// <summary>
    /// Spec 7.2.16: Corporate buyback — steady buy pressure on stocks with buyback programs.
    /// Simulated as a small upward bias on profitable large-cap stocks.
    /// </summary>
    private void ApplyCorporateBuybacks(IReadOnlyList<Stock> stocks)
    {
        foreach (var stock in stocks)
        {
            if (stock.Traits.Contains("ETF")) continue;
            if (stock.NetIncome <= 0 || stock.MarketCap < 5_000_000_000m) continue;

            // ~10% of eligible stocks have active buyback programs
            if (_rng.NextDouble() > 0.10) continue;

            // Steady buying: up to 25% of average daily volume (Rule 10b-18)
            var buyVolume = (long)(stock.AverageVolume * 0.005 * _rng.NextDouble());
            stock.DayVolume += buyVolume;

            // Small upward pressure
            var push = stock.CurrentPrice * 0.0002m * (decimal)_rng.NextDouble();
            stock.CurrentPrice = Math.Round(stock.CurrentPrice + push, 2);

            // === REALISM BATCH 2: Buybacks reduce SharesOutstanding ===
            // Companies repurchase ~0.01-0.03% of shares per buyback day
            var repurchasePct = 0.0001 + _rng.NextDouble() * 0.0002; // 0.01-0.03%
            var sharesRepurchased = (long)(stock.SharesOutstanding * repurchasePct);
            if (sharesRepurchased > 0 && stock.SharesOutstanding - sharesRepurchased > 1_000_000)
            {
                stock.SharesOutstanding -= sharesRepurchased;
            }
        }
    }
}
